name: Surf
description: Stateful programmatic web browsing in Go.
baseurl: http://headzoo.io/surf
paginate: 10
permalink: pretty
destination: _site
safe: false
lsi: false
timezone: America/New_York
encoding: utf-8
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap